#!/usr/bin/env sh
ALLMAILQUERY='( is:spam OR NOT is:spam ) AND ( is:deleted OR NOT is:deleted ) AND ( is:muted OR NOT is:muted )'

CACHE="$HOME/.cache/keywsync"
LASTMOD="$CACHE/lastmod"
BEFORE="$CACHE/before"

mkdir -p "$CACHE"

# Synchronize tags local-to-remote (-t), now all tag changes done in the
# notmuch db are synchronized with the message files (preferably using a
# lastmod: query [1] which catches messages where have been done after the
# revision of the db at the time of the last remote-to-local synchronization)

if [ ! -e "$LASTMOD" ] ; then
	echo '-1' > "$LASTMOD"
fi

lastmod=`expr $(cat $LASTMOD) + 1`

# ``Alternatively, store the revision from before the local-to-remote sync. In
# that way it is possible to detect local changes that happened during the
# sync. This will re-check the messages that were modified as part of the
# remote-to-local sync.''
notmuch_get_revision "$HOME/.mail" > $LASTMOD

keywsync -m "$HOME/.mail" -t -p -q "lastmod:$lastmod.. AND ($ALLMAILQUERY)" --no-replace-chars

# Save the current unix time: $ before_offlineimap=$( date +%s )

date +%s > "$BEFORE"

# Run offlineimap to synchronize your local maildir and messages with the
# remote. According to the offlineimap documentation [0] the X-Keywords flags
# are synchronized in the same way as maildir flags (whatever that means [2]).
# (NOTHING TO DO)

# SEE postsynchook FOR THE REST
