#!/usr/bin/env sh
ALLMAILQUERY='( is:spam OR NOT is:spam ) AND ( is:deleted OR NOT is:deleted ) AND ( is:muted OR NOT is:muted )'

CACHE="$HOME/.cache/keywsync"
LASTMOD="$CACHE/lastmod"
NEXTMOD="$CACHE/nextmod"
BEFORE="$CACHE/before"
STATE="$CACHE/state"

mkdir -p "$CACHE"

# Synchronize tags local-to-remote (-t), now all tag changes done in the
# notmuch db are synchronized with the message files (preferably using a
# lastmod: query [1] which catches messages where have been done after the
# revision of the db at the time of the last remote-to-local synchronization)

if [ ! -e "$LASTMOD" ] ; then
	echo '-1' > "$LASTMOD"
fi

if [ ! -e "$STATE" ] ; then
	echo 0 > "$STATE"
fi

state=$(cat $STATE)

# ``Alternatively, store the revision from before the local-to-remote sync. In
# that way it is possible to detect local changes that happened during the
# sync. This will re-check the messages that were modified as part of the
# remote-to-local sync.''
if [ $state -eq 0 ] ; then
	echo
	echo '@#! pre/0' ;
	notmuch_get_revision "$HOME/.mail" > "$NEXTMOD"
	echo 1 > "$STATE"
	state=1
fi

if [ $state -eq 1 ] ; then
	echo
	echo '@#! pre/1' ;
	lastmod=`expr $(cat $LASTMOD) + 1`
	beforesync=$(cat "$NEXTMOD")
	keywsync -m "$HOME/.mail" -t -p -q "lastmod:$lastmod..$beforesync AND ($ALLMAILQUERY)" --no-replace-chars
	echo 2 > "$STATE"
	state=2
fi

if [ $state -eq 2 ] ; then
	echo
	echo '@#! pre/2' ;
	cat "$NEXTMOD" > "$LASTMOD"
	echo 3 > "$STATE"
	state=3
fi

# Save the current unix time: $ before_offlineimap=$( date +%s )

if [ $state -eq 3 ] ; then
	echo
	echo '@#! pre/3' ;
	date +%s > "$BEFORE"
	echo 4 > "$STATE"
	state=4
fi

# Run offlineimap to synchronize your local maildir and messages with the
# remote. According to the offlineimap documentation [0] the X-Keywords flags
# are synchronized in the same way as maildir flags (whatever that means [2]).
# (NOTHING TO DO)

# SEE postsynchook FOR THE REST
