#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

pacman_installed="$(pacman -Q | cut -d' ' -f1)"
npm_installed="$(ls -1 "$(npm root -g)")"
yarn_installed="$(jq -r < /usr/local/share/.config/yarn/global/package.json '.dependencies | keys[]')"
pip_installed="$(pip list --format freeze | cut -d'=' -f1)"

function _a ( ) {
  if { <<< "$pacman_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
    pacman -R "$1"
  fi
}

function _p ( ) {
  if { <<< "$pacman_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
    exit
  fi
  if { <<< "$pip_installed" grep "^$2\$" 1>/dev/null 2>&1 ; } ; then
    pip uninstall "$2"
  fi
}

function _n ( ) {
  if { <<< "$pacman_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
    exit
  fi
  if { <<< "$npm_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
    npm uninstall -g "$1"
  fi
  if { <<< "$yarn_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
    yarn global remove "$1"
  fi
}

# Arch & AUR
_a fzf
_a st
_a rxvt-unicode
_a keybase-release
_a xkblayout-state
_a abunchoftags
_a offlineimap
_a exa-git
_a flashplugin
_a hangups-git
_a qtox
_a toxcore
_a yaourt
_a package-query
_a tealdeer-git
_a pdftk
_a pdftk-bin
_a libgcj17-bin
_a phantomjs
_a impressive
_a pcmciautils
_a webkitgtk

# Python / pip
_p python-cssselect cssselect
_p autopep8 autopep8
_p python-lxml lxml
_p tldr tldr

# Node / NPM
_n jshint
_n jslint
_n gulp
_n uglify-js
_n peerflix
_n torrentflix
_n ora # others should depend on this
_n np # should be installed as dev dep
_n xyz # should be installed as dev dep
_n jspm # not using it at the moment
_n grunt-cli # install via arch repo
