#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function _a ( ) {
  pacman -Qi "$1" 2>/dev/null && pacman -R "$1"
}

function _p ( ) {
  { pacman -Ss "$1" | grep '\[installed\]' 1>/dev/null ; } || { pip show "$2" && pip uninstall "$2" ; }
}

function _n ( ) {
  if ls "$(npm root -g)" --color=never | grep '^'"$1"'$' 1>/dev/null 2>&1 ; then
    npm uninstall -g "$1"
  fi
}

# Arch / pacman + yaourt
_a fzf
_a st
_a rxvt-unicode
_a keybase-release
_a xkblayout-state
_a abunchoftags
_a offlineimap
_a exa-git
_a flashplugin

# Python / pip
_p python-cssselect cssselect
_p autopep8 autopep8
_p python-lxml lxml
_p tldr

# Node / NPM
_n jshint
_n jslint
_n gulp
_n uglify-js
