#!/usr/bin/env bash

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

"$DOTFILES/bootstrap/dotfiles-diff-list" | \
xargs -I{} git --no-pager diff --no-index --color-words "$HOME/{}" "$DOTFILES/{}";

exit 0
