#!/usr/bin/env bash

function doIt() {

	mkdir -p "$HOME/.bin"
	mkdir -p "$HOME/.opt"
	mkdir -p "$HOME/.mail"
	mkdir -p "$HOME/.config"
	mkdir -p "$HOME/.config/newsbeuter"
	mkdir -p "$HOME/.config/dotfiles"
	mkdir -p "$HOME/.local/share"
	mkdir -p "$HOME/.local/share/newsbeuter"

	mkdir -p "$HOME/dev"
	mkdir -p "$HOME/ulb"
	mkdir -p "$HOME/games"
	mkdir -p "$HOME/shots"
	mkdir -p "$HOME/sandbox"

	DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

	rsync \
		--exclude ".git/" \
		--exclude ".gitmodules" \
		--exclude "bootstrap/" \
		--exclude "files/" \
		--exclude "modules/" \
		--exclude "README.md" \
		--exclude "LICENSE" \
		-avhL --no-perms \
		"$DOTFILES"/ "$HOME"/ 1>/dev/null;

	source "$HOME/.bash_profile";

	_DOTFILES="$(readlink -f "$DOTFILES")"
   	_LOCATION="$HOME/.config/dotfiles/location"
	echo " * writing '$_DOTFILES' to $_LOCATION"
	echo "$_DOTFILES" > "$_LOCATION"

}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	doIt;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		doIt;
	fi;
fi;
unset doIt;
