#!/usr/bin/env bash

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

rsync \
	--exclude ".git/" \
	--exclude ".gitmodules" \
	--exclude "bootstrap/" \
	--exclude "files/" \
	--exclude "modules/" \
	--exclude "README.md" \
	--exclude "LICENSE" \
	-avnchL \
	"$DOTFILES"/ "$HOME"/ | \
	tail -n +2 | \
	head -n -3 | \
	grep -v '/$' ;
