#!/usr/bin/env bash

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

rsync \
	--exclude ".git/" \
	--exclude ".github/" \
	--exclude ".gitmodules" \
	--exclude ".bin/bun/node_modules/" \
	--exclude ".bin/bun/dist/" \
	--exclude "bootstrap/" \
	--exclude "Makefile" \
	--exclude "README.md" \
	--exclude "LICENSE" \
	-avnchl \
	"$DOTFILES"/ "$HOME"/ | \
	tail -n +2 | \
	head -n -3 | \
	grep -v '/$' ;
