#!/usr/bin/env bash

function doIt() {

	mkdir -p "$HOME/.bin"
	mkdir -p "$HOME/.opt"
	mkdir -p "$HOME/.mail/draft"
	mkdir -p "$HOME/.config"
	mkdir -p "$HOME/.config/newsbeuter"
	mkdir -p "$HOME/.config/dotfiles"
	mkdir -p "$HOME/.config/new/models"
	mkdir -p "$HOME/.local/share"
	mkdir -p "$HOME/.local/share/newsbeuter"

	mkdir -p "$HOME/ac"
	mkdir -p "$HOME/dev"
	mkdir -p "$HOME/shots"
	mkdir -p "$HOME/sandbox"
	mkdir -p "$HOME/notes"

	mkdir -p "$HOME/dl"
	mkdir -p "$HOME/share"
	mkdir -p "$HOME/library/audio/music"
	mkdir -p "$HOME/library/picture"
	mkdir -p "$HOME/library/video"


	DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

	rsync \
		--exclude ".git/" \
		--exclude ".github/" \
		--exclude ".gitmodules" \
		--exclude ".bin/bun/node_modules/" \
		--exclude ".bin/bun/dist/" \
		--exclude "bootstrap/" \
		--exclude "Makefile" \
		--exclude "README.md" \
		--exclude "LICENSE" \
		-avhl --no-perms \
		"$DOTFILES"/ "$HOME"/ 1>/dev/null;

	# shellcheck source=.bash_profile
	source "$HOME/.bash_profile";

	_DOTFILES="$(readlink -f "$DOTFILES")"
   	_LOCATION="$HOME/.config/dotfiles/location"
	echo " * writing '$_DOTFILES' to $_LOCATION"
	echo "$_DOTFILES" > "$_LOCATION"

}

if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
	doIt;
else
	read -r -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		doIt;
	fi;
fi;
unset doIt;
