#!/usr/bin/env bash

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

"$DOTFILES/bootstrap/dotfiles-diff-list" | \
xargs -I{} env GIT_PAGER="diff-so-fancy" git diff --no-index "$HOME/{}" "$DOTFILES/{}";

exit 0
