#!/usr/bin/env bash

if [ "$(id -u)" = 0 ] ; then
	echo 'must NOT be run as root'
	exit 1
fi

cd /tmp || exit 123

fail() {
	echo 'could not install aura'
	exit 1
}

i() {
	wget "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz" || fail
	tar -xvf "$1".tar.gz && rm "$1".tar.gz
	sh -c "cd $1 && makepkg -si --skippgpcheck" || { rm -r "$1" && fail ; }
	rm -r "$1"
}

if ! command -v aura 1>/dev/null 2>&1 ; then
	echo 'installing aura'
	sudo pacman -S wget --noconfirm --needed
	i aura-bin
fi

if ! command -v aura 1>/dev/null 2>&1 ; then
	fail
fi

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

packages="$(sed -e 's/\s*#.*$//g' -e '/^$/d' "$DOTFILES"/bootstrap/packages/aur)"

echo "  > installing ~ $(<<< "$packages" tr '\n' ' ')"
comm -23 \
	<(printf '%s\n' "$packages" | sort) \
	<(printf '%s\n' "$packages" | pacman -Qk - 2>/dev/null | cut -d: -f1 | sort) |
xargs -r aura -A --noconfirm

exit 0
