#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

O="$(mktemp /tmp/update.out.XXXXXXXX)"
E="$(mktemp /tmp/update.err.XXXXXXXX)"

function _exit ( ) {
  rm -f "$O" "$E"
  exit "$1"
}

function _do ( ) {
  "$@" 1>"$O" 2>"$E"
  _check "$?"
}

function _check ( ) {
  if [ "$1" -ne 0 ] ; then
    echo '! NONZERO RETURN CODE'
    echo ' > There was an error!'
    >&1 cat "$O"
    >&2 cat "$E"
    _exit "$1"
  fi
}

function _trap ( ) {
  echo '! TRAP'
  echo ' > There was an error!'
  _exit 70;
}

trap _trap SIGHUP SIGINT SIGTERM

function i ( ) {
  echo "  > installing ~ $@"
  _do pacman -S --needed --noconfirm "$@"
}

# Fonts
i extra/ttf-dejavu \
powerline-fonts \
ttf-font-awesome

# X
i xorg-xkill \
xsel xclip \
xfig \
xorg-xwininfo xorg-xprop

# Notifications
i xorg-xrdb \
inotify-tools \
libnotify \
dunst

# Main apps
i bash-completion \
gvim \
firefox \
evince \
mupdf

# Compilers and package managers
i nodejs npm yarn grunt-cli \
pypy3 \
go

# Python 3 packages
i python-pip \
python-six \
python-lxml \
python-jedi \
python-docopt \
python-pygments \
python-networkx \
python-numpy \
python-sympy \
python-matplotlib \
python-scipy \
python-pillow \
python-cssselect \
python-click \
python-tqdm \
python-oauth2client \
python-google-api-python-client \
python-keyring \
autopep8

# Python 2 packages
i python2-xlib \
python2-numpy \
python2-lxml \
python2-keyring

# Video
i ffmpeg vlc \
youtube-dl atomicparsley

# File parsing
i highlight atool w3m poppler libcaca

# useful
i testdisk \
pstoedit uniconvertor \
inkscape \
ack \
the_silver_searcher \
fasd \
at \
acpi \
udevil \
ntp \
phantomjs \
nmap \
go-ipfs

# Keys and Passwords
i gnupg \
pass \
keybase

# Messaging
i qtox

# Presentations
i impressive

# Typing training
i klavaro

# RSS
# i newsbeuter # does not exist anymore

# Torrents
i transmission-gtk

# Mail
i gmime \
notmuch \
notmuch-runtime \
msmtp

# Security
i openssh

# Disk usage
i ncdu

# iPhone / USB
i usbmuxd gvfs-afc \
tumbler thunar \
exfat-utils

# Image manipulation
i scrot \
screenfetch \
libjpeg-turbo gifsicle optipng \
feh eog imagemagick fbida \
gimp \
viewnior

# Libre office
i libreoffice-still

# Latex
i extra/texlive-bibtexextra \
extra/texlive-bin \
extra/texlive-core \
extra/texlive-fontsextra \
extra/texlive-formatsextra \
extra/texlive-games \
extra/texlive-genericextra \
extra/texlive-htmlxml \
extra/texlive-humanities \
extra/texlive-langchinese \
extra/texlive-langcyrillic \
extra/texlive-langextra \
extra/texlive-langgreek \
extra/texlive-langjapanese \
extra/texlive-langkorean \
extra/texlive-latexextra \
extra/texlive-music \
extra/texlive-pictures \
extra/texlive-plainextra \
extra/texlive-pstricks \
extra/texlive-publishers \
extra/texlive-science

# Plotting
i gnuplot \
transfig geogebra

# Indexing with recoll
i recoll \
pstotext \
antiword \
catdoc \
unrtf \
id3lib \
mutagen python-mutagen \
python2-pychm \
perl-image-exiftool \
aspell-en \
libxslt \
djvulibre \
python2

# Fix recoll filters
sed 's:^#!/usr/bin/env python$:#!/usr/bin/env python2:g' -i /usr/share/recoll/filters/*
sed 's:^#!/usr/bin/python$:#!/usr/bin/env python2:g' -i /usr/share/recoll/filters/*

# Lesspipe
i lesspipe \
perl \
rpmextract \
fastjar \
unzip \
unrar \
p7zip \
cabextract \
cdrtools \
html2text \
antiword \
unrtf \
imagemagick

# File system
i rclone

# Music
i mpd ncmpcpp

# HTTP monitoring
i ngrep tcpdump

_exit 0
