#!/usr/bin/env bash

if [ "$(id -u)" != 0 ] ; then
  echo 'must be run as root'
  exit 1
fi

O="$(mktemp --tmpdir "${USER}-install-arch-out.XXXXXXXX")"
E="$(mktemp --tmpdir "${USER}-install-arch-err.XXXXXXXX")"

function _exit ( ) {
  rm -f "$O" "$E"
  exit "$1"
}

function _do ( ) {
  "$@" 1>"$O" 2>"$E"
  _check "$?"
}

function _check ( ) {
  if [ "$1" -ne 0 ] ; then
    echo '! NONZERO RETURN CODE'
    echo ' > There was an error!'
    >&1 cat "$O"
    >&2 cat "$E"
    _exit "$1"
  fi
}

# shellcheck disable=SC2317
function _trap ( ) {
  echo '! TRAP'
  echo ' > There was an error!'
  _exit 70;
}

trap _trap SIGHUP SIGINT SIGTERM

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE[0]}")")";

packages="$(sed -e 's/\s*#.*$//g' -e '/^$/d' "$DOTFILES"/bootstrap/packages/arch)"

echo "  > installing ~ $(<<< "$packages" tr '\n' ' ')"
_do pacman -S --needed --noconfirm - <<< "$packages"

# Fix recoll filters
sed 's:^#!/usr/bin/env python$:#!/usr/bin/env python2:g' -i /usr/share/recoll/filters/*
sed 's:^#!/usr/bin/python$:#!/usr/bin/env python2:g' -i /usr/share/recoll/filters/*

_exit 0
