#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function i ( ) {
  1>/dev/null 2>&1 pacman -S --needed --noconfirm "$@"
}

i ranger
i xorg-xrdb
i inotify-tools
i terminator
i bash-completion
i gvim
i firefox
i evince
i nodejs npm
i pypy3
i python-pip
i python-six
i python-lxml
i python-jedi
i python-docopt
i python-pygments
i python-networkx
i python-numpy
i python-scipy
i python-pillow
i python-cssselect
i autopep8
i python2-xlib
i go
i transmission-gtk
i ffmpeg vlc
i pulseaudio pulseaudio-alsa pavucontrol
i rhythmbox brasero
i testdisk
i pstoedit python2-numpy python2-lxml uniconvertor
i inkscape
i ack
i the_silver_searcher
i at
i cups
i acpi
i xorg-xkill
i xsel xclip
i gnupg
i pass
i keybase
i qtox
i impressive
i klavaro

i newsbeuter

i offlineimap
i msmtp

i openssh
i python2-keyring
i python-keyring

# replace ugly default font
i extra/ttf-dejavu

# disk usage

i ncdu

# iphone / USB

i usbmuxd gvfs-afc
i tumbler thunar
i exfat-utils

# image manipulation

i scrot
i screenfetch
i libjpeg-turbo gifsicle optipng
i feh imagemagick
i gimp
i viewnior

# libre office

i libreoffice-still

# latex

i extra/texlive-bibtexextra \
extra/texlive-bin \
extra/texlive-core \
extra/texlive-fontsextra \
extra/texlive-formatsextra \
extra/texlive-games \
extra/texlive-genericextra \
extra/texlive-htmlxml \
extra/texlive-humanities \
extra/texlive-langchinese \
extra/texlive-langcjk \
extra/texlive-langcyrillic \
extra/texlive-langextra \
extra/texlive-langgreek \
extra/texlive-langjapanese \
extra/texlive-langkorean \
extra/texlive-latexextra \
extra/texlive-music \
extra/texlive-pictures \
extra/texlive-plainextra \
extra/texlive-pstricks \
extra/texlive-publishers \
extra/texlive-science

i gnuplot
i xfig transfig geogebra
i xorg-xwininfo xorg-xprop

# recoll

## opt dept
i pstotext
i antiword
i catdoc
i unrtf
# i untex
i id3lib
i mutagen python-mutagen
i python2-pychm
i perl-image-exiftool
i aspell-en

## already installed
i libxslt
i poppler
i djvulibre
i python2

## main
i recoll
