#!/usr/bin/env sh

if [ $(id -u) == "0" ] ; then
echo 'must NOT be run as root'
exit 1
fi

cd /tmp

function fail {
	echo 'could not install pacaur'
	exit 1
}

function i {
	wget "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz" || fail
	tar -xvf "$1".tar.gz && rm "$1".tar.gz
	sh -c "cd $1 && makepkg -si --skippgpcheck" || { rm -r "$1" && fail ; }
	rm -r "$1"
}

if ! which pacaur 1>/dev/null 2>&1 ; then
	echo 'installing pacaur'
	sudo pacman -S expac yajl git --noconfirm --needed
	i cower
	i pacaur
fi

if ! which pacaur 1>/dev/null 2>&1 ; then
	fail
fi

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

packages="$(sed '/^$/d' "$DOTFILES"/bootstrap/packages/aur | grep -v '^#')"

echo "  > installing ~ $(<<< $packages tr '\n' ' ')"
pacaur -Sa --needed --noconfirm --noedit - <<< "$packages"

exit 0
