#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

packages="$(sed -e 's/\s*#.*$//g' -e '/^$/d' "$DOTFILES"/bootstrap/packages/base)"

echo "  > installing ~ $(<<< $packages tr '\n' ' ')"
1>/dev/null 2>&1 pacman -S --needed --noconfirm - <<< "$packages"

exit 0
