#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function _ ( ) {
  if ! ls "$(npm root -g)" --color=never | grep '^'"$1"'$' 1>/dev/null 2>&1 ; then
    npm install -g "$1"
  fi
}

_ semver
_ npm

_ yarn
_ n
_ jshint
_ peerflix
_ torrentflix
_ uglify-js
_ npm-check-updates
_ jspm
_ xyz
_ yo
_ grunt-cli
_ gulp
_ tick
_ speed-test
_ man-n
_ np
_ babel-cli
_ esdoc
_ ava-codemods
_ xo
