#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function i ( ) {
  1>/dev/null 2>&1 pacman -S --needed --noconfirm "$@"
}

i lsb-release
i cmake
i make
i clang
i gcc
i curl
i wget
i zip unzip
i unrar
i git
i rsync
i jq
i base-devel
i pkgfile
i bind-tools
i thefuck
i tk

i xorg-xinit
i i3-wm i3lock i3status
i terminator xterm
i fish
i ranger
i xorg-xrandr
i alsa-utils
i pulseaudio pulseaudio-alsa pavucontrol
i cups gtk3-print-backends
