#!/usr/bin/env sh

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

echo " * base"
sudo sh "$DOTFILES"/bootstrap/install-base || exit "$?"
echo " * arch"
sudo sh "$DOTFILES"/bootstrap/install-arch || exit "$?"
echo " * aur"
sh "$DOTFILES"/bootstrap/install-aur || exit "$?"
echo " * npm"
sudo sh "$DOTFILES"/bootstrap/update-npm i || exit "$?"
echo " * pip"
sudo sh "$DOTFILES"/bootstrap/update-pip i || exit "$?"
