#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function i ( ) {
  1>/dev/null 2>&1 pacman -S --needed --noconfirm "$@"
}

i ranger \
highlight atool w3m poppler libcaca

i xorg-xrdb \
inotify-tools \
terminator \
bash-completion \
gvim \
firefox \
evince \
nodejs npm

i python-pip \
python-six \
python-lxml \
python-jedi \
python-docopt \
python-pygments \
python-networkx \
python-numpy \
python-scipy \
python-pillow \
python-cssselect \
autopep8

i pypy3

i python2-xlib
i go

i ffmpeg vlc \
pulseaudio pulseaudio-alsa pavucontrol \
rhythmbox brasero

i testdisk \
pstoedit python2-numpy python2-lxml uniconvertor \
inkscape \
ack \
the_silver_searcher \
at \
cups \
acpi \
udevil

i xorg-xkill \
xsel xclip

i gnupg \
pass \
keybase

i qtox
i impressive
i klavaro

i newsbeuter
i transmission-gtk

i offlineimap \
msmtp

i openssh
i python2-keyring
i python-keyring

# replace ugly default font
i extra/ttf-dejavu

# disk usage

i ncdu

# iphone / USB

i usbmuxd gvfs-afc \
tumbler thunar \
exfat-utils

# image manipulation

i scrot \
screenfetch \
libjpeg-turbo gifsicle optipng \
feh imagemagick \
gimp \
viewnior

# libre office

i libreoffice-still

# latex

i extra/texlive-bibtexextra \
extra/texlive-bin \
extra/texlive-core \
extra/texlive-fontsextra \
extra/texlive-formatsextra \
extra/texlive-games \
extra/texlive-genericextra \
extra/texlive-htmlxml \
extra/texlive-humanities \
extra/texlive-langchinese \
extra/texlive-langcjk \
extra/texlive-langcyrillic \
extra/texlive-langextra \
extra/texlive-langgreek \
extra/texlive-langjapanese \
extra/texlive-langkorean \
extra/texlive-latexextra \
extra/texlive-music \
extra/texlive-pictures \
extra/texlive-plainextra \
extra/texlive-pstricks \
extra/texlive-publishers \
extra/texlive-science

i gnuplot \
xfig transfig geogebra \
xorg-xwininfo xorg-xprop

# recoll

i recoll \
pstotext \
antiword \
catdoc \
unrtf \
id3lib \
mutagen python-mutagen \
python2-pychm \
perl-image-exiftool \
aspell-en \
libxslt \
djvulibre \
python2
