#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

x="$1"

if [ "$x" = u ] ; then

  function i ( ) {
    if pip show "$1" 1>/dev/null 2>&1 ; then
      pip install --upgrade "$1" 1>/dev/null
    fi
  }

elif [ "$x" = i ] ; then

  function i ( ) {
    if ! pip show "$1" 1>/dev/null 2>&1 ; then
      pip install "$1" 1>/dev/null
    fi
  }

else

  function i ( ) {
    if pip show "$1" 1>/dev/null 2>&1 ; then
      pip install --upgrade "$1" 1>/dev/null
    else
      pip install "$1" 1>/dev/null
    fi
  }

fi

i arrow==0.4.2 # for compat with ics
i ics
i tldr
i ptpython
i semantic_version
