#!/usr/bin/env sh

if [ $(id -u) != "0" ]; then
  echo 'must be run as root'
  exit 1
fi

if false; then
#if command -v yarn 1>/dev/null; then

  echo "  # using yarn"

  yarn_installed="$(jq -r < /usr/local/share/.config/yarn/global/package.json '.dependencies | keys[]' 2>/dev/null)"

  function _ ( ) {
    if ! { <<< "$yarn_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
      echo "  > installing ~ $@"
      yarn global add "$@"
    fi
  }

  function _update {
    echo "  - upgrade global packages"
    yarn global upgrade --latest || exit "$?"
  }

elif command -v npm 1>/dev/null; then

  echo "  # using npm"

  npm_installed="$(ls -1 "$(npm root -g)")"

  function _ ( ) {
    if ! { <<< "$npm_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
      echo "  > installing ~ $@"
      npm install -g "$@"
    fi
  }

  function _update {
    echo "  - update global packages"
    npm update -g || exit "$?"
  }

else
  echo 'yarn or npm is not installed, install one via pacman first'
  exit 2
fi

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

packages="$(sed -e 's/\s*#.*$//g' -e '/^$/d' "$DOTFILES"/bootstrap/packages/node)"

function _install ( ) {
  echo "  - install global packages"
  for package in $packages ; do
    _ "$package"
  done
}

x="${1:-i}"

export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
if [ "$x" = i ] ; then
  _install
elif [ "$x" = u ] ; then
  _update
else
  echo "Option $x is not valid."
  exit 3
fi
unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
