#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function + ( ) {
  if ! ls "$(npm root -g)" --color=never | grep '^'"$1"'$' 1>/dev/null 2>&1 ; then
    npm install -g "$1"
  fi
}

+ semver
+ npm

npm update -g

+ n
+ jshint
+ peerflix
+ torrentflix
+ uglify-js
+ npm-check-updates
+ jspm
+ xyz
+ yo
+ grunt-cli
+ gulp
+ tick
+ speed-test
+ man-n
+ np
+ babel-cli
+ esdoc
+ ava-codemods
+ xo
