#!/usr/bin/env sh

if [ $(id -u) == "0" ] ; then
echo 'must NOT be run as root'
exit 1
fi

TMP="$(mktemp /tmp/extra.sh.XXXXXXXX)"

cd "$TMP"

git clone https://github.com/gauteh/abunchoftags || exit $?
cd abunchoftags/dist/archlinux || exit $?
makepkg -si

rm -rf "$TMP"
