#!/usr/bin/env sh

if [ $(id -u) != "0" ]; then
  echo 'must be run as root'
  exit 1
fi

if ! command -v npm 1>/dev/null; then
  echo 'npm is not installed, install it via pacman first'
  exit 2
fi

function _install ( ) {
  #echo "  - overwrite semver/npm arch linux packages"
  #_ semver
  #_ npm

  echo "  - install global packages"
  #_ yarn
  _ n
  _ eslint
  _ eslint_d
  _ babel-eslint
  _ eslint-plugin-babel
  _ npm-check-updates
  _ fixpack
  _ yo
  #_ grunt-cli
  _ gulp-cli
  _ tick
  _ man-n
  _ babel-cli
  _ esdoc
  _ journally
  _ geez
  _ zxcvbn
  _ ava-codemods
  _ speed-test
  _ texshake

  export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
  _ puppeteer
  unset PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
}

if false && command -v yarn 1>/dev/null; then

  echo "  # using yarn"

  function _ ( ) {
    yarn global add "$@"
  }

  function _update {
    _install
  }

else

  echo "  # using npm"

  npm_installed="$(ls -1 "$(npm root -g)")"

  function _ ( ) {
    if ! { <<< "$npm_installed" grep "^$1\$" 1>/dev/null 2>&1 ; } ; then
      echo "  > installing ~ $@"
      npm install -g "$@"
    fi
  }

  function _update {
    #echo "  - overwrite semver/npm arch linux packages"
    #npm install -g semver npm || exit "$?"
    echo "  - update global packages"
    npm update -g || exit "$?"
  }

fi


x="$1"

if [ "$x" = u ] ; then
  _update
elif [ "$x" = i ] ; then
  _install
else
  _install
fi
