#!/usr/bin/env sh

if [ $(id -u) != "0" ]
then
echo 'must be run as root'
exit 1
fi

function i ( ) {
  if pip show "$1" 1>/dev/null 2>&1 ; then
    pip install --upgrade "$1"
  else
    pip install "$1"
  fi
}


i arrow
i ics
i tldr
i ptpython
