#!/usr/bin/env sh

DOTFILES="$(dirname "$(dirname "${BASH_SOURCE}")")";

sudo pacman -Syyu || exit "$?"
yaourt -Syyu --aur || exit "$?"
npm update -g || exit "$?"
sudo sh "$DOTFILES"/bootstrap/update-pip u || exit "$?"
