#!/usr/bin/env sh

archive="${HOME}/archive"
mkdir -p "${archive}"

timestamp="$(now)"

for file in "$@" ; do
	dest="${archive}/$(os.path.sanitize "${timestamp}-$(basename "${file}")")"
	cp "${file}" "${dest}"
done
