#!/usr/bin/env python3

import sys

from offline import get_arg_parser
from offline import get_params
from offline import get_state
from offline import download_once

from arxiv import DEFAULTS
from arxiv import get_uid
from arxiv import get_resources

def main ( kwargs ) :

    params = get_params(kwargs, DEFAULTS)
    _state = get_state('state', params)

    return download_once( _state = _state , get_uid = get_uid , get_resources =
            get_resources, **params )

if __name__ == '__main__':
    parser = get_arg_parser(description='arxiv-downloader')
    args = parser.parse_args()
    rc = main(vars(args))
    sys.exit(rc)
