#!/usr/bin/env python3

import sys

from offline import get_arg_parser
from offline import get_params
from offline import get_state
from offline import index_daemon

from arxiv import DEFAULTS
from arxiv import generate_tags
from arxiv import compile_metadata

def main ( kwargs ) :

    params = get_params ( kwargs , DEFAULTS )
    _state = get_state('index_state', params)

    return index_daemon( _state = _state , compile_metadata = compile_metadata,
            generate_tags=generate_tags, **params )

if __name__ == '__main__':
    parser = get_arg_parser()
    args = parser.parse_args()
    rc = main(vars(args))
    sys.exit(rc)
