#!/bin/env bash

# This is a general-purpose function to ask Yes/No questions in Bash, either
# with or without a default answer. It keeps repeating the question until it
# gets a valid answer.

# http://djm.me/ask

if [ "${2:-}" = "Y" ]; then
    prompt="Y/n"
    default=Y
elif [ "${2:-}" = "N" ]; then
    prompt="y/N"
    default=N
else
    prompt="y/n"
    default=
fi

while true; do

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read REPLY </dev/tty

    # Default?
    if [ -z "$REPLY" ]; then
        REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
        Y*|y*) exit 0 ;;
        N*|n*) exit 1 ;;
    esac

done
