#!/usr/bin/env sh

output="$(arch-audit --color never --show-cve --upgradable)"
excode="$?"

if [ -n "$output" ] ; then
	if [ "$excode" -eq 0 ] ; then
		printf '%s' "$output"
	else
		>&2 printf '%s' "$output"
	fi
fi

exit "$excode"
