#!/usr/bin/env sh

prev=flat

CONFIG="$HOME/.config/autorotate/config"

while true; do
	orientation="$(orientation)"
	if [ $orientation != flat ] && [ $orientation != $prev ] ; then
		jq -r '.devices[]' "$CONFIG" | xargs -d'\n' rotate $orientation
		prev=$orientation
	fi
	sleep 3
done
