#!/usr/bin/env sh

prev=flat

while true; do
	orientation="$(orientation)"
	if [ $orientation != flat ] && [ $orientation != $prev ] ; then
		rotate $orientation
		prev=$orientation
	fi
	sleep 3
done
