#!/usr/bin/env dash

result="$(printf '%s\n' "scale=10;$*" | bc --mathlib | tr -d '\\\n')"
if printf '%s' "$result" | grep -q '[.]' ; then
	# improve the output for decimal numbers
	printf '%s\n' "$result" |
	sed -e 's/^\./0./'        `# add "0" for cases like ".5"` \
		-e 's/^-\./-0./'      `# add "0" for cases like "-.5"`\
		-e 's/0*$//;s/\.$//'   # remove trailing zeros
else
	printf '%s\n' "$result"
fi
