#!/usr/bin/env sh

cwd="${1:-.}"

output=""

locals=$(git -C "$cwd" status --porcelain -u | wc -l)

if [ "$locals" -gt 0 ] ; then
	output="$output $(printf "local[%s]" "$locals")"
fi

branch=$(git -C "$cwd" symbolic-ref --quiet --short HEAD 2>/dev/null)
handles=$(git -C "$cwd" branch -r)
remotes=$(git -C "$cwd" remote)

for remote in "$remotes"; do
	handle="$remote/$branch"
	if grep "$handle" 1>/dev/null <<< "$handles"; then
		pulls=$(git -C "$cwd" log "HEAD..$handle" --oneline | wc -l)
		pushs=$(git -C "$cwd" log "$handle..HEAD" --oneline | wc -l)
		if [ "$pulls" -gt 0 ] || [ "$pushs" -gt 0 ] ; then
			output="$output $(printf "%s[pull:%s, push:%s]" "$remote" "$pulls" "$pushs")"
		fi
	fi
done

if [ "$output" != '' ] ; then
	echo "$output" | tail -c +2
	exit 1
fi
