#!/usr/bin/env sh

CACHE="${HOME}/.cache/cineonu"
CONFIG="${HOME}/.config/cineonu/config"

ROOT="https://www.unric.org"
LANG="en"
BASEURI="${ROOT}/${LANG}"

function log {
	>&2 echo "$@"
}

if [ ! -f "${CONFIG}" ] ; then
	log "Missing config file @ ${CONFIG}"
	exit 2
fi

FROM="$(jq -r < "${CONFIG}" .mailfrom)"
TO=$(jq -r < "${CONFIG}" .mailto[])

function hash {
	xxhsum - <<< "$1" 2>/dev/null | head -c 16
}

function getmetadata() {
	url="$(jq -r <<< "$1" .url)"
	title="$(jq -r <<< "$1" .title)"
	log "Downloading ${title} (${url})"
	curl "${url}" | cineonu-parse-event
}

function enqueue() {
	kind="$1"
	metadata="$2"
	url="$(jq -r <<< "$metadata" .url)"
	title="$(jq -r <<< "$metadata" .title)"
	log "Enqueueing ${title} (${url})"
	subject="${kind} CINEONU event: ${title}"

	cineonu-format-event "${metadata}" | \
	courriel.compose._prompt \
		--stdin \
		--yolo \
		--from "${FROM}" \
		--to ${TO} \
		--subject "${subject}" | \
	msmtp-enqueue-only -t --read-envelope-from
}

function main() {

	year="$(date '+%Y')"

	url="${BASEURI}/${year}"
	storagedir="${CACHE}/${year}"
	urldir="${storagedir}/url"
	datdir="${storagedir}/dat"

	mkdir -p "${urldir}"
	mkdir -p "${datdir}"

	log "Downloading Index for ${year} (${url})"
	html="$(curl "${url}")"

	if [ "$?" -ne 0 ] ; then exit 1 ; fi

	events="$(cineonu-parse-list <<< "${html}")"

	run=0

	while read -r event; do

		metadata="$(getmetadata "${event}")"
		if [ "$?" -ne 0 ] ; then continue ; fi

		url="$(jq -r <<< "$metadata" .url)"
		if [ "$?" -ne 0 ] ; then continue ; fi

		dat_key="$(hash "$metadata")"
		url_key="$(hash "$url")"

		dat_file="${datdir}/${dat_key}"
		url_file="${urldir}/${url_key}"

		if [ ! -f "${dat_file}" ] ; then

			run=1

			kind=Updated
			if [ ! -f "${url_file}" ] ; then
				kind=New
				echo "${url}" > "${url_file}"
			fi

			enqueue "${kind}" "${metadata}"
			jq <<< "${metadata}" > "${dat_file}"

		fi

	done <<< "$(jq --compact-output '.events[]' <<< ${events})"

	if [ "${run}" -gt 0 ] ; then msmtp-runqueue ; fi

}

main
