#!/usr/bin/env sh

METADATA="$1"

k() {
	key="$1"
	value="$(printf '%s' "$METADATA" | jq -r ."$key")"
	if [ "$value" != 'null' ] ; then
		printf '%s: %s\n' "$key" "$value"
	fi
}

k url
k year
k title
k date
k time
k location
k runtime
k img
k trailer
k imdb
k facebook
k eventbrite
k bozar

printf '\n%s\n' Description
printf '%s\n\n' '=='

printf '%s' "$METADATA" | jq -r .description
