#!/usr/bin/env sh

CACHE="${HOME}/.cache/cineonu"
CONFIG="${HOME}/.config/cineonu/config"

ROOT="https://www.unric.org"
LANG="en"
BASEURI="${ROOT}/${LANG}"

if [ ! -f "${CONFIG}" ] ; then
	>&2 echo "Missing config file @ ${CONFIG}"
	exit 2
fi

FROM="$(jq -r < "${CONFIG}" .mailfrom)"
TO=$(jq -r < "${CONFIG}" .mailto[])

function enqueue() {
	url="$(jq -r <<< "$1" .url)"
	title="$(jq -r <<< "$1" .title)"
	echo "${title} (${url})"
	metadata="$(curl "${url}" | cineonu-parse-event)"
	subject="New CINEONU event: ${title}"

	cineonu-event-format "${metadata}" | \
	courriel.compose._prompt \
		--stdin \
		--yolo \
		--from "${FROM}" \
		--to ${TO} \
		--subject "${subject}" | \
	msmtp-enqueue-only -t --read-envelope-from
}

function main() {

	year="$(date '+%Y')"

	url="${BASEURI}/${year}"
	storage="${CACHE}/${year}"
	mkdir -p "${storage}"

	next="${storage}/next.json"
	prev="${storage}/prev.json"

	if [ ! -f "${prev}" ] ; then
		echo '{"events":[]}' > "${prev}"
	fi

	tmp="$(curl "${url}")"

	if [ "$?" -ne 0 ] ; then
		exit 1
	fi

	<<< "${tmp}" cineonu-parse-list | jq > "${next}"

	run=0
	diff="$(cineonu-list-diff "${prev}" "${next}")"
	if [ -n "${diff}" ] ; then
		while read -r event; do
			run=1
			enqueue "${event}"
		done <<< "${diff}"
	fi

	if [ "${run}" -gt 0 ] ; then msmtp-runqueue ; fi

	mv "${next}" "${prev}"

}

main
