#!/usr/bin/env sh

CACHE="${HOME}/.cache/cineonu"

ROOT="https://www.unric.org"
LANG="en"
BASEURI="${ROOT}/${LANG}"

FROM="aurelien.ooms@gmail.com"
to="$@"

function enqueue() {
	url="$(jq -r <<< "$1" .url)"
	title="$(jq -r <<< "$1" .title)"
	echo "${title} (${url})"
	metadata="$(curl "${url}" | cineonu-parse-event)"
	subject="New CINEONU event: ${title}"

	cineonu-event-format "${metadata}" | \
	courriel.compose._prompt \
		--stdin \
		--yolo \
		--from ${FROM} \
		--to ${to} \
		--subject "${subject}" | \
	msmtp-enqueue-only -t --read-envelope-from
}

function main() {

	year="$(date '+%Y')"

	url="${BASEURI}/${year}"
	storage="${CACHE}/${year}"
	mkdir -p "${storage}"

	next="${storage}/next.json"
	prev="${storage}/prev.json"

	curl "${url}" | cineonu-parse-list | jq > "${next}"

	if [ -f "${prev}" ] ; then

		run=0
		diff="$(cineonu-list-diff "${prev}" "${next}")"
		if [ -n "${diff}" ] ; then
			while read -r event; do
				run=1
				enqueue "${event}"
			done <<< "${diff}"
		fi

		if [ "${run}" -gt 0 ] ; then msmtp-runqueue ; fi

	fi

	mv "${next}" "${prev}"

}

main
