#!/usr/bin/env bash

# Get a character's Unicode code point
perl -e "use utf8; print sprintf('U+%04X', ord(\"$@\"))";
# print a newline unless we're piping the output to another program
if [ -t 1 ]; then
	echo ""; # newline
fi;
