#!/usr/bin/env sh

# https://en.wikipedia.org/wiki/URI
URI_REGEXP='^[a-zA-Z][a-zA-Z0-9+.-]*://'
FILE_URI_REGEXP='^file://'
HTML2TEXT_OPTIONS='--decode-errors ignore --links-after-para --mark-code --ignore-images --dash-unordered-list -b 79 --reference-links'

function isURI {

	<<< "$1" grep -q "$URI_REGEXP"

}

# https://en.wikipedia.org/wiki/File_URI_scheme
function isFileURI {

	<<< "$1" grep -q "$FILE_URI_REGEXP"

}

function getPathFromURI {

	<<< "$1" sed "s%${URI_REGEXP}%%"

}

function copyAndOpen {

	tmp="$(mktemp --tmpdir "${USER}-cp-and-open.XXXXXXXX")"

	filetype="$(xdg-mime query filetype "$1")"

	case "$filetype" in
	'text/html')
		html2text $HTML2TEXT_OPTIONS -- "$1" | sed 's/\s*$//' > "$tmp"
		;;
	*)
		cp "$1" "$tmp"
		;;
	esac

	open "$tmp"

}

function open {
	xdg-open "$1" &
}

for arg in "$@" ; do

	if isURI "$arg" ; then

		if isFileURI "$arg" ; then

			path="$(getPathFromURI "$arg")"

			copyAndOpen "$path"

		else

			open "$arg"

		fi

	else

		copyAndOpen "$arg"

	fi

done
