#!/usr/bin/env sh

key="$1"

if [ "$key" = 'ports' ] ; then
  URL='https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers'
  OPTIONS=''
elif [ "$key" = 'currencies' ] ; then
  URL='https://en.wikipedia.org/wiki/List_of_circulating_currencies'
  OPTIONS='--pad-tables'
fi

if [ -n "$URL" ] ; then
  curl -s -L "$URL" | html-select table.wikitable | html2text --decode-errors replace -b 0 --reference-links $OPTIONS | less -S
fi
