#!/usr/bin/env sh

key="$1"

if [ "$key" = 'ports' ] ; then
  URL='https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers'
  curl -s -L "$URL" | html-select table.wikitable | html2text --decode-errors replace -b 0 --reference-links | less -S
fi
