#!/usr/bin/env sh

if [ "$#" -lt 2 ] ; then
  >&2 printf '%s\n' "Not enough arguments."
  >&2 printf '%s\n' "Syntax is: $0 <root> <dst> [...<additional rsync args>]"
  exit 1
fi

root="$1" && shift
dst="$1" && shift
src='.'

printf '%s\n' 'Params'
printf ' root: %s\n' "$root"
printf '  dst: %s\n' "$dst"
printf 'rsync: %s\n' "$*"
printf '%s\n' '==============='

printf '%s' 'Generating file list...'

DANGLING="$(mktemp --tmpdir "${USER}-dangling-backup-list.XXXXXXXX")"

#dangling -z -c -1 | tr '\0\n' '\n\0' | rev | cut -d' ' -f2- | rev | tr '\0\n' '\n\0' > "$DANGLING"
dangling -z -r "$root" -c -1 | sed -z 's/.\{2\}$//' > "$DANGLING"

printf '%s\n' ' DONE'
printf '%s\n' '==============='

n="$(< "$DANGLING" tr '\0\n' '\n\0' | wc -l)"

printf '%s\n' 'Number of files'
printf '%s\n' "$n"
printf '%s\n' '==============='

human_size="$(du --files0-from "$DANGLING" -ch | tail -1 | cut -f1)"

printf '%s\n' 'Storage'
printf '%s\n' "$human_size"
printf '%s\n' '==============='

printf '%s\n' 'Overview'
< "$DANGLING" tr '\0\n' '\n\0' | head -5
printf '%s\n' '...'
printf '%s\n' '==============='

if ask "Backup ${n} files (${human_size}) from '${src}' to '${dst}'?" ; then
  set -x
  rsync -0 -avP "$@" --files-from "$DANGLING" "$src" "$dst"
fi
