#!/usr/bin/env sh

# all arguments are passed to find
# if no arguments are passed it will use the default 'find . -type f'
# if the output is redirected it will list the selected files
# otherwise it will prompt for their deletion at the end of the selection

if [ "$#" -eq 0 ] ; then set -- . -type f ; fi

if [ -t 1 ] ; then
  selected="$(mktemp --tmpdir dedup_XXXXXXXX)"
else
  selected='/dev/null'
fi

find "$@" | \
duplicates.group | \
duplicates.select | \
tee "$selected"

if [ "$selected" != '/dev/null' ] ; then

  if [ "$(wc -l < "$selected")" -ge 1 ] ; then

    if ask 'Do you really want to delete those files?' 'N' ; then
      while read -r path; do
        >&2 printf 'Deleting "%s"\n' "$path"
        rm -f -- "$path"
      done < "$selected"
    fi

  else
    >&2 printf 'No duplicates to delete\n'
  fi

  rm -f "$selected"

fi
