#!/usr/bin/env bash

matches="$(rg --color never --no-heading --column --only-matching --hidden -g '!.git/*' --smart-case "$@")"
if [ -z "$matches" ] ; then
	exit 1
fi

args="$(echo "$matches" | yank -l -d $'\n\r' | rev)"

if [ -z "$args" ] ; then
	exit 2
fi

line="$(echo "$args" | cut -d: -f3 | rev)"
column="$(echo "$args" | cut -d: -f2 | rev)"
filename="$(echo "$args" | cut -d: -f1-3 --complement | rev)"

vim "+call cursor($line,$column)" "$filename"
