#!/usr/bin/env bash

# Determine size of a file or total size of a directory
if du -b /dev/null > /dev/null 2>&1 ; then
	arg=-sbh
else
	arg=-sh
fi
if [ $# -ne 0 ] ; then
	du $arg -- "$@"
else
	du $arg ./.[^.]* ./*
fi
