#!/usr/bin/env bash

FROM="${1^^}"
TO="${2^^}"
AMOUNT="${3:-1}"
DATE="${4:-latest}"
ACCESS_KEY="${5:-$(pass data.fixer.io/api/access_key)}"

URL="http://data.fixer.io/api/$DATE?access_key=$ACCESS_KEY&symbols=$FROM,$TO"

RESPONSE="$(curl --silent "$URL")"

if [ "$RESPONSE" = '' ] ; then
  >&2 echo "ERROR: Could not access '$URL'"
  exit 1
fi

SUCCESS="$(printf '%s' "$RESPONSE" | jq .success)"

if [ "$SUCCESS" = 'false' ] ; then
  CODE="$(printf '%s' "$RESPONSE" | jq .error.code)"
  TYPE="$(printf '%s' "$RESPONSE" | jq .error.type)"
  INFO="$(printf '%s' "$RESPONSE" | jq .error.info)"
  >&2 echo "ERROR in response for '$URL':"
  >&2 echo " > $CODE [$TYPE] $INFO"
  exit 2
fi

RATE_FROM="$(printf '%s' "$RESPONSE" | jq ".rates.$FROM")"
RATE_TO="$(printf '%s' "$RESPONSE" | jq ".rates.$TO")"

if [ "$RATE_FROM" = '' ] || [ "$RATE_TO" = '' ] ; then
  >&2 echo "Could not interpret response:"
  >&2 echo "$RESPONSE"
  exit 1
fi

COMPUTATION="scale=6; $AMOUNT * $RATE_TO / $RATE_FROM"
echo "$AMOUNT $FROM = $(echo "$COMPUTATION" | bc) $TO"
