#!/usr/bin/env sh

FROM="${1^^}"
TO="${2^^}"
AMOUNT="${3:-1}"
DATE="${4:-latest}"
ACCESS_KEY="${5:-$(pass data.fixer.io/api/access_key)}"

URL="http://data.fixer.io/api/$DATE?access_key=$ACCESS_KEY&symbols=$FROM,$TO"

RESPONSE="$(curl --silent $URL)"

if [ "$RESPONSE" = '' ] ; then
  >&2 echo "Could not access `$URL`"
  exit 1
fi

RATE_FROM="$(<<< "$RESPONSE" jq ".rates.$FROM")"
RATE_TO="$(<<< "$RESPONSE" jq ".rates.$TO")"

if [ "$RATE_FROM" = '' ] || [ "$RATE_TO" = '' ] ; then
  >&2 echo "Could not interpret response:"
  >&2 echo "$RESPONSE"
  exit 1
fi

COMPUTATION="scale=6; $AMOUNT * $RATE_TO / $RATE_FROM"
echo "$AMOUNT $FROM = $(echo "$COMPUTATION" | bc) $TO"
