#!/usr/bin/env bash

# Show all the names (CNs and SANs) listed in the SSL certificate
# for a given domain
if [ -z "${1}" ]; then
	echo "ERROR: No domain specified.";
	exit 1;
fi;

domain="${1}";
echo "Testing ${domain}\u2026";
echo ""; # newline

tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
	| openssl s_client -connect "${domain}:443" -servername "${domain}" 2>&1);

if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
	certText=$(echo "${tmp}" \
		| openssl x509 -text -certopt "no_aux, no_header, no_issuer, no_pubkey, \
		no_serial, no_sigdump, no_signame, no_validity, no_version");
	echo "Common Name:";
	echo ""; # newline
	echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//" | sed -e "s/\/emailAddress=.*//";
	echo ""; # newline
	echo "Subject Alternative Name(s):";
	echo ""; # newline
	echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
		| sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2;
	exit 0;
else
	echo "ERROR: Certificate not found.";
	exit 1;
fi;
