#!/usr/bin/env sh

EXEPATH="$0"
EXE="$(basename "$EXEPATH")"

_usage ( ) {
  if [ "$1" "$2" "$3" ] ; then
    >&2 echo "usage: $EXE $4"
    exit 2
  fi
}

_usage "$#" -lt 1 "<command> <...args>"

CMD="$1"
shift

CONFIGDIR="$HOME/.config/gitdns"
CONFIG="$CONFIGDIR/config"
DNS="$CONFIGDIR/dns"
DNSGITDIR="$DNS/.git"
CNAME="CNAME"

_dns ( ) {
  gitkv "$DNS" "$@"
}

# check config files exists
if [ ! -e "$CONFIG" ] ; then
  >&2 echo "Could not find configuration file $CONFIG"
  exit 1
fi

# set up dns repo
if [ ! -e "$DNSGITDIR" ] ; then

  remote="$(< "$CONFIG" jq -r .remote)"

  if [ "$?" -ne 0 ] ; then
    >&2 echo "Failed to read remote from $CONFIG"
    exit 1
  fi

  mkdir -p "$DNS"

  _dns init "$remote"

fi

_route ( ) {

  case "$CMD" in
      info)
	  _info "$@"
	  ;;
      put)
	  _put "$@"
	  ;;
      get)
	  _get "$@"
	  ;;
      sync)
	  _sync "$@"
	  ;;
      *)
	  _unknown_command "$CMD"
	  ;;
  esac
}

_info ( ) {

  _usage "$#" -ne 0 "info"

  echo "EXE       = $EXE"
  echo "EXEPATH   = $EXEPATH"
  echo "CONFIGDIR = $CONFIGDIR"
  echo "CONFIG    = $CONFIG"
  echo "DNS       = $DNS"
  echo "DNSGITDIR = $DNSGITDIR"
  echo "CNAME     = $CNAME"

  exit 0

}

_put ( ) {

  _usage "$#" -ne 2 "put <hostname> <ip>"

  _dns put "$CNAME/$1" "$2"

  exit "$?"

}

_get ( ) {

  _usage "$#" -ne 1 "get <hostname>"

  _dns get "$CNAME/$1"

  exit "$?"

}

_sync ( ) {

  _usage "$#" -ne 0 "sync"

  _dns sync

  exit "$?"

}

_unknown_command ( ) {
  >&2 echo "Unknown command: $1"
  exit 3
}

_route "$@"
