#!/usr/bin/env sh

q="$(ui.dialog.input -p '' -sb '#1851CE')"

if [ -z "$q" ] ; then
	exit 1
fi

query=$(printf '%s' "$q" | urlencode)

wb --new-window 'https://google.com/search?tbm=isch&q='"$query"
