#!/usr/bin/env sh

echo "$@"

if man "$1" 2>/dev/null ; then exit ; fi

if ! command -v "$1" >/dev/null ; then
  >&2 echo "Could not find command '$1'."
fi

if 2>&1 "$@" --help | less -r ; then exit ; fi

if 2>&1 "$@" -h | less -r ; then exit ; fi

if tldr "$@" 2>/dev/null ; then exit ; fi

if code "$1" ; then exit ; fi
