#!/usr/bin/env python3

import sys
import lxml.html as html
from lxml.cssselect import CSSSelector

sel = lambda h, s: CSSSelector(s)(h)

selector = ' '.join(sys.argv[1:])

tree = html.parse(sys.stdin)

nodes = sel(tree, selector)

for node in nodes:
    raw = html.tostring(node)
    # sys.stdout.buffer.write(raw)
    # sys.stdout.write('\n')
    print(raw.decode())
