#!/usr/bin/env python3

import sys
import lxml.html as html
from lxml.cssselect import CSSSelector

sel = lambda h, s: CSSSelector(s)(h)

selector = 'body > *'

tree = html.parse(sys.stdin)

METHODS = {
    'text': lambda x: x.text,
    'content': lambda x: x.text_content(),
    'string': lambda x: html.tostring(x).decode(),
}

method = sys.argv[1]

nodes = sel(tree, selector)

for node in nodes:
    string = METHODS[method](node)
    print(string)
