#!/usr/bin/env node

const fs = require('fs') ;
const filename = process.argv[2] ;
const YAML = require('js-yaml') ;

const readStream = fs.createReadStream( filename || '/dev/stdin' ) ;
const writeStream = process.stdout ;

let json = '';

readStream.on('data', function (chunk) { json += chunk; });

readStream.on('end', function () {
  const data = JSON.parse(json);
  const yaml = YAML.dump(data);
  writeStream.write(yaml);
  writeStream.write('\n');
});
