#!/usr/bin/env python3

import sys
import json
import os.path
import getpass
import argparse
import subprocess
import urllib.parse
import urllib.request

API = 'https://api.mobilevikings.be/v3'

CONFIG = os.path.expanduser('~/.config/api.mobilevikings.be')
OAUTH2 = os.path.join(CONFIG, 'oauth2')
TOKEN = os.path.join(OAUTH2, 'token')

CACHE = os.path.expanduser('~/.cache/api.mobilevikings.be')
MSISDNS = os.path.join(CACHE, 'msisdns')

_pass = lambda key : subprocess.check_output(['pass', key]).decode().strip()

CLIENT_ID = _pass('api.mobilevikings.be/client_id')
CLIENT_SECRET = _pass('api.mobilevikings.be/client_secret')

def main ( ):

    global ARGS

    parser = argparse.ArgumentParser()
    parser.add_argument('--verbose', '-v', action='count', default=0)

    subparsers = parser.add_subparsers(dest='action_name')
    subparsers.required = True

    parser_auth = subparsers.add_parser('auth')
    parser_auth.set_defaults(action=auth)

    parser_balance = subparsers.add_parser('balance')
    parser_balance.set_defaults(action=balance)

    ARGS = parser.parse_args()

    return ARGS.action( )

def auth ( ):

    username, password = _user_credentials()

    return _oauth2_access_token_password ( username , password )


def balance ( ):

    me = _me_msisdn()

    res = _api_request( 'GET' , '/msisdns/{msisdn}/balance'.format( msisdn = me ) )

    json.dump(res, sys.stdout, indent=4)
    print()


def _me_msisdn ( ):

    try:
        with open(MSISDNS) as f:
            msisdns = json.load(f)

    except Exception as e:
        msisdns = _api_request( 'GET' , '/msisdns' )

        os.makedirs(os.path.dirname(MSISDNS))
        with open(MSISDNS, 'w') as f: json.dump(msisdns, f)

    return msisdns['results'][0]['msisdn']


def _api_request ( method, endpoint ) :

    url = API + endpoint

    if ARGS.verbose > 0:
        print(method, url, file=sys.stderr)

    token = _token()

    headers = {
        'Authorization': 'Bearer {}'.format(token['access_token']) ,
        'Accept': 'application/json' ,
    }

    req = urllib.request.Request(url, headers=headers, method=method)

    with urllib.request.urlopen(req) as f:
        res = json.load(f)

    return res


def _user_credentials ():

    username = input('username: ')
    password = getpass.getpass('password: ')

    return username, password

def _token ( ):

    try:
        with open(TOKEN) as f:
            token = json.load(f)
    except Exception as e:
        print('Failed to read access token. Are you authenticated (mbv auth)?')
        raise e

    return token

def _oauth2_access_token ( parameters ):

    method = 'POST'
    endpoint = '/oauth2/access_token'
    data = urllib.parse.urlencode(parameters).encode()

    req = urllib.request.Request(API+endpoint, data=data, method=method)
    with urllib.request.urlopen(req) as f: res = json.load(f)

    json.dump(res, sys.stdout, indent=4) # log

    os.makedirs(os.path.dirname(TOKEN))
    with open(TOKEN, 'w') as f: json.dump(res, f)

def _oauth2_access_token_password ( username , password ) :

    parameters = {
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET,
        'grant_type': 'password',
        'username': username,
        'password': password,
    }

    return _oauth2_access_token ( parameters )

def _oauth2_access_token_refresh_token ( token ):

    parameters = {
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET,
        'grant_type': 'refresh_token',
        'refresh_token': token['refresh_token'],
    }

    return _oauth2_access_token ( parameters )

if __name__ == '__main__':
    main()
