#!/usr/bin/env sh

if [ $(id -u) == "0" ] ; then
  echo 'must NOT be run as root'
  exit 1
fi

COUNTRIES="${1:-country=BE&country=FR&country=DE&country=LU&country=NL}"
OPTIONS="${2:-protocol=https&ip_version=4}"
URL="https://www.archlinux.org/mirrorlist/?${COUNTRIES}&${OPTIONS}"
SOURCE="$(mktemp --tmpdir "${USER}-mirup-mirrorlist-source.XXXXXXXX")"
RANKED="$(mktemp --tmpdir "${USER}-mirup-mirrorlist-ranked.XXXXXXXX")"
PACMAN=/etc/pacman.d/mirrorlist

echo "Downloading ${URL}"

curl "${URL}" > "${SOURCE}" || exit 10

echo "Cleaning up downloaded file ..."

sed -i '/^##/d' "${SOURCE}"
sed -i 's/^#Server/Server/g' "${SOURCE}"

echo "Ranking mirrors ..."

rankmirrors -v "${SOURCE}" | tee "${RANKED}"

if grep -q '^Server = https' "${RANKED}" ; then

  echo "Overwriting configuration ..."

  sudo chown root:root "${RANKED}"
  sudo chmod 744 "${RANKED}"
  sudo mv "${RANKED}" "${PACMAN}"

else

  echo 'Not overwriting configuration because resulting file does not contain any `^Server = https` line.'

fi

echo "Cleaning up ..."
rm "${SOURCE}"
