#!/usr/bin/env bash

MSMTPDIR="${HOME}/.msmtp"
QUEUEDIR="${MSMTPDIR}/queue"
CANCELEDDIR="${MSMTPDIR}/canceled"
LOCKFILE="${QUEUEDIR}/.lock"
MAXWAIT=120

OPTIONS=$@

echo "[=======] Greetings! This is msmtp-cancel ()_()"
echo "[=======] Running queue '$QUEUEDIR'"
echo "[=======] With options '$OPTIONS'"
echo "[=======] Canceled jobs will be put in '$CANCELEDDIR'"

# Jump to queue directory (create it if necessary)
if ! cd "$QUEUEDIR" ; then
	echo "[~~~~~~~] Cannot use '$QUEUEDIR' *_*"
	exit 1
fi

if ! mkdir -p "$CANCELEDDIR" || [ ! -d "$CANCELEDDIR" ] ; then
	echo "[~~~~~~~] Cannot use '$CANCELEDDIR' *_*"
	exit 1
fi


echo "[=======] Waiting $MAXWAIT seconds to acquire lockfile '$LOCKFILE' [<]"

# wait for a lock that another instance might have set
exec {LOCKFD}>"$LOCKFILE"
if ! flock -x -w "$MAXWAIT" "$LOCKFD" ; then
	echo "[~~~~~~~] Waited $MAXWAIT seconds for"
	echo "[~~~~~~~] lockfile '$LOCKFILE', giving up -_-"
	exit 1
fi

echo "[=======] Looking for emails to cancel ..( °°) [x]"

# check for empty queuedir
if [ "`echo *.mail`" = '*.mail' ]; then
	echo "[=======] No emails in '$QUEUEDIR' è_é"
	echo "[=======] Have a good day!"
	exit 0
fi

echo "[=======] Canceling emails that I found ^_^"

# process all emails
for MAILFILE in *.mail; do
	echo "[*******] Canceling '$MAILFILE' ..."
	MSMTPFILE="`echo $MAILFILE | sed -e 's/mail/msmtp/'`"
	mv "$MAILFILE" "$CANCELEDDIR"
	if ! mv "$MSMTPFILE" "$CANCELEDDIR" ; then
		echo "[WARNING] Could not find '$MSMTPFILE' matching '$MAILFILE' :("
	fi
done

echo "[=======] Canceled all emails I could find. Have a good day!"

exit 0
