#!/usr/bin/env bash

QUEUEDIR="$HOME/.msmtp/queue"
LOCKFILE="$QUEUEDIR/.lock"

# Set secure permissions on created directories and files
umask 077

echo "[=======] Greetings! This is msmtp-enqueue []_[]"
echo "[=======] Running queue '$QUEUEDIR' with options '$OPTIONS'"

# Jump to queue directory (create it if necessary)
if ! mkdir -p "$QUEUEDIR" || ! cd "$QUEUEDIR" ; then
	echo "[~~~~~~~] Cannot use '$QUEUEDIR' *_*"
	exit 1
fi

echo "[=======] Waiting to acquire lockfile '$LOCKFILE' [<]"

# wait for a lock that another instance might have set
exec {LOCKFD}>"$LOCKFILE"
flock -x "$LOCKFD"

# Create new unique filenames of the form
# MAILFILE:  ccyy-mm-dd-hh.mm.ss[-x].mail
# MSMTPFILE: ccyy-mm-dd-hh.mm.ss[-x].msmtp
# where x is a consecutive number only appended if you send more than one
# mail per second.
BASE="`date +%Y-%m-%d-%H.%M.%S`"
if [ -f "$BASE.mail" -o -f "$BASE.msmtp" ]; then
	TMP="$BASE"
	i=1
	while [ -f "$TMP-$i.mail" -o -f "$TMP-$i.msmtp" ]; do
		i=`expr $i + 1`
	done
	BASE="$BASE-$i"
fi
MAILFILE="$BASE.mail"
MSMTPFILE="$BASE.msmtp"

# Write command line to $MSMTPFILE
if ! echo "$@" > "$MSMTPFILE" ; then
	echo "[~~~~~~~] Could not write '$MSMTPFILE' *_*"
	rm -f "$MSMTPFILE"
	exit 1
fi

# Write the mail to $MAILFILE
if ! cat > "$MAILFILE" ; then
	echo "[~~~~~~~] Could not write '$MAILFILE' *_*"
	rm -f "$MSMTPFILE" "$MAILFILE"
	exit 1
fi

echo "[SUCCESS] Your email has been added to the queue!"

flock -u "$LOCKFD"

exit 0
