#!/usr/bin/env bash

QUEUEDIR="$HOME/.msmtpqueue"
LOCKFILE="$QUEUEDIR/.lock"
MAXWAIT=120

OPTIONS=$@

echo "[=======] Greetings! This is msmtp-runqueue ()_()"
echo "[=======] Running queue '$QUEUEDIR'"
echo "[=======] With options '$OPTIONS'"

# Jump to queue directory (create it if necessary)
if ! mkdir -p "$QUEUEDIR" || ! cd "$QUEUEDIR" ; then
	echo "[~~~~~~~] Cannot use '$QUEUEDIR' *_*"
	exit 1
fi

echo "[=======] Waiting $MAXWAIT seconds to acquire lockfile '$LOCKFILE' [<]"

# wait for a lock that another instance might have set
exec {LOCKFD}>"$LOCKFILE"
if ! flock -x -w "$MAXWAIT" "$LOCKFD" ; then
	echo "[~~~~~~~] Waited $MAXWAIT seconds for"
	echo "[~~~~~~~] lockfile '$LOCKFILE', giving up -_-"
	exit 1
fi

echo "[=======] Looking for emails to send ..( °°) [x]"

# check for empty queuedir
if [ "`echo *.mail`" = '*.mail' ]; then
	echo "[=======] No emails in '$QUEUEDIR' è_é"
	echo "[=======] Have a good day!"
	exit 0
fi

echo "[=======] Sending emails that I found ^_^"

# process all emails
for MAILFILE in *.mail; do
	MSMTPFILE="`echo $MAILFILE | sed -e 's/mail/msmtp/'`"
	echo "[*******] Sending '$MAILFILE' to `sed -e 's/^.*-- \(.*$\)/\1/' $MSMTPFILE` ..."
	if [ ! -f "$MSMTPFILE" ]; then
		echo "[FAILURE] Could not find '$MSMTPFILE' matching '$MAILFILE' :("
		continue
	fi
	msmtp $OPTIONS `cat "$MSMTPFILE"` < "$MAILFILE"
	if [ $? -eq 0 ]; then
		rm "$MAILFILE" "$MSMTPFILE"
		echo "[SUCCESS] '$MAILFILE' sent successfully :)"
	else
		echo "[FAILURE] Could not send '$MAILFILE' :("
	fi
done

echo "[=======] Reached the end of the queue. Have a good day!"

exit 0
