#!/usr/bin/env bash

msmtp-enqueue-only "$@"

SENDDELAY=1

if [ "$SENDDELAY" -gt 0 ] ; then
	echo "[=======] Waiting 30 seconds just to let you enough time to cancel that"
	msmtp-runqueue-daemon-30s
else
	msmtp-runqueue-daemon-now
fi

exit 0
