#!/usr/bin/env bash

QUEUEDIR="${HOME}/.msmtp/queue"

while read -r i ; do
	grep -E -s --colour -h '(^From:|^To:|^Subject:)' "$i" || echo "No mail in queue";
	echo " "
done < <(find "$QUEUEDIR" -name '*.mail')
