#!/usr/bin/env python3

import sys
import json
import fileinput

root = {
    'children' : [ ] ,
    'page' : 1 ,
}

stack = [ root ]

currentlvl = 0

for line in fileinput.input():
    line = line[:-1]
    parts = line.split('\t')
    title, parameters = parts[-2:]
    page_s = parameters.split(',')[0] # i.e. #444,-18,622
    page = int(page_s[1:]) # remove the `#` before the page number
    lvl = len(parts) - 2
    if lvl == currentlvl + 1: # should check for error here
        stack.append(stack[-1]['children'][-1])
    elif lvl < currentlvl:
        for i in range(currentlvl - lvl):
            stack.pop()
    currentlvl = lvl
    currentparent = stack[-1]
    currentparent['children'].append({
        'title': title,
        'page': page,
        'children': [],
    })

json.dump(root, sys.stdout)
