#!/usr/bin/env sh

_running="$(uname -r)"
_lts="$(<<< "$_running" grep '\-\lts$' -o)"
_installed="$(pacman -Q linux"$_lts")"

running="$(<<< "${_running}" sed 's/-ARCH$//g' | sed 's/\.0-/-/g' | tr '.-' ':')"
installed="$(<<< "${_installed}${_lts}" cut -d' ' -f2 | tr '.-' ':')"

>&2 echo "running=$running"
>&2 echo "installed=$installed"

if [ "$running" != "$installed" ] ; then
	exit 0
else
	exit 1
fi
