#!/usr/bin/env sh

_running="$(uname -r)"
_lts="$(printf '%s' "$_running" | grep '\-lts$' -o)"
_installed="$(pacman -Q linux"$_lts")"

running="$(printf '%s' "${_running}" | tr '.-' ':' | sed 's/:arch/:/')"
installed="$(printf '%s' "${_installed}${_lts}" | cut -d' ' -f2 | tr '.-' ':' | sed 's/:arch/:/')"

>&2 printf 'running=%s\n' "$running"
>&2 printf 'installed=%s\n' "$installed"

test "$running" != "$installed"
