#!/usr/bin/env python3

# script to compute the orientation of a tablet device
# requires python-pyudev
# stolen from https://github.com/freundTech/surface-tools/blob/bfe4483d48c4ec858c30c6cbd486847dcec73fc0/autorotate/autorotate

# import sys
import pyudev

sensorname="accel_3d"

# def twos_comp(val):
    # if val & (1 << (16-1)) != 0: val = val - (1 << 16)
    # return val

def getOrientation(accelX, accelY, relative=5, absolute=200000): #, accelZ):
    absAccelX = abs(accelX)
    absAccelY = abs(accelY)
    # absAccelZ = abs(accelZ)

    # print(absAccelX, file=sys.stderr)
    # print(absAccelY, file=sys.stderr)

    if absAccelY >= relative * absAccelX and absAccelY >= absolute:
        return "inverted" if accelY > 0 else "normal"
    elif absAccelX >= relative * absAccelY and absAccelX >= absolute:
        return "left" if accelX > 0 else "right"

    return "flat"

def checkRotation(device):
    accelX = device.attributes.asint("in_accel_x_raw")
    accelY = device.attributes.asint("in_accel_y_raw")
    # accelZ = device.attributes.asint("in_accel_z_raw")

    return getOrientation(accelX, accelY) #, accelZ)

if __name__ == "__main__":
    context = pyudev.Context()
    device = None
    for device in context.list_devices(subsystem="iio").match_attribute("name", sensorname): break
    assert device is not None
    path = device.device_path
    device = pyudev.Devices.from_path(context, path)
    print(checkRotation(device))
