#!/usr/bin/env sh

OUTPUT_DIR="$(mktemp --tmpdir --directory "${USER}-parallel-map.XXXXXXXX.d")"

i=0
while read -r line ; do
  ((++i))
  "$@" <<< "$line" > "${OUTPUT_DIR}/${i}" &
done < /dev/stdin

wait $(jobs -p)

cat "${OUTPUT_DIR}"/*

rm -rf "${OUTPUT_DIR}"
