#!/usr/bin/env bash
shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

for password in "${password_files[@]}"; do
  echo -n "$password "
  pass show "$password"
done
