#!/usr/bin/env sh

input="$1"
root="${2:-.}"
selector="${3:-select(true)}"

if [ -n "$root" ] ; then
  mkdir -p "$root"
fi

args="$(mktemp --tmpdir "${USER}-pdf-burst-chapters-commands.XXXXXXXX")"

_exit() {
  rm -f "$args"
  exit "$@"
}

i=0

mutool show "$input" outline | \
mutool-outline-tojson | \
mutool-json-outline-format | \
#jq -c '.children[] | select(.title|test("^[1-9][0-9]* "))' |
#jq -c '.children[] | select(.title | startswith("I")) | .children[]' |
jq -c '.children[] | '"$selector" | \
while IFS= read -r chapter; do
  i=$((i+1))
  title="$(printf '%s' "$chapter" | jq -r .title | trim)"
  begin="$(printf '%s' "$chapter" | jq -r .begin)"
  end="$(printf '%s' "$chapter" | jq -r .end)"
  if [ "$end" != 'N' ] ; then
    end="$((end-1))"
  fi
  ii="$(printf %03d "$i")"
  echo "${begin}-${end}" "${ii} ${title}" | tee --append "$args"
done

if ! vim "$args" ; then _exit 11 ; fi

while IFS= read -r line || [ -n "$line" ] ; do
  output="${root}/$(printf '%s' "$line" | sed 's/^[^ ]* //').pdf"
  range="$(printf '%s' "$line" | cut -d' ' -f1)"
  mutool merge -o "$output" "$input" "$range"
done < "$args"

_exit 0
