#!/usr/bin/env sh

if [ "$#" -eq 0 ] ; then
  pkg-parse
else
  for uri in "$@" ; do
    case "$uri" in
      http*) curl -L "$uri" | pkg-parse ;;
      *) pkg-parse "$uri" ;;
    esac
  done
fi | sort -u
