#!/usr/bin/env sh

pacman -Qi |
grep '^Name\|^Installed Size' |
cut -d: -f2 |
cut -c2- |
paste - - |
awk -F'\t' 'BEGIN{ s["MiB"]=1048576; s["KiB"]=1024; s["B"]=1;} {split($2, a, " "); printf "%.0f %s\n", a[1] * s[a[2]], $1}' |
sort -n
