#!/usr/bin/env bash

# rotate script for surface pro 3 on Xorg
# depends on xorg-xrandr, xorg-xinput, and xf86-input-wacom

# if it breaks, update by looking at output of xinput

CONFIG="$HOME/.config/autorotate/config"

jq -r '.devices[]' "$CONFIG" | xargs -d'\n' rotate-devices "$1"
