#!/usr/bin/env sh

FILE="$HOME/notes/scratchpad.md"
ID=VIMSCRATCHPAD

if [ "$(vim --serverlist | grep -c "$ID")" -eq 0 ] ; then
  terminator -b -x vim --servername "$ID" "$FILE"
fi

i3-msg "[title=$ID] focus"
