#!/usr/bin/env sh

engine="https://duckduckgo.com/"

what="$(ui.dialog.input -p '' -sb '#3B3242')"

if [ "$what" != '' ] ; then
	query="$(head -c -1 <<< "$what" | urlencode)"
	wb --new-window "${engine}?q=${query}"
fi
