#!/usr/bin/env sh

engine="https://duckduckgo.com/html"

what="$(ui.dialog.input -p '' -sb '#3B3242')"

if [ -n "$what" ] ; then
	query="$(printf '%s' "$what" | urlencode)"
	wb --new-window "${engine}?q=${query}"
fi
