#!/bin/bash
#
# Inspired by https://gist.github.com/asmz/84734cdc0a18e72eec25
#
# Usage
#  slack-notifications-for-conversation <channel_id>
#
# Configuration
#  Requires SLACK_API_TOKEN environment variable.
#
# Requirements
#  *) curl
#  *) jq - command-line JSON processor
#     http://stedolan.github.io/jq/
#

channel_id="$(jq -r '.id')"
endpoint='conversations.info'

slack-api-fetch "$endpoint" "channel=${channel_id}"
