#!/usr/bin/env sh

CACHE="$HOME/.cache/sncb-nmbs"
STATIONS="$CACHE/stations"

#echo 'loading stations...'
#curl -s -H 'accept: application/json' https://irail.be/stations/nmbs > "$STATIONS"

station="$(\
curl -s -H 'accept: application/json' https://irail.be/stations/nmbs | \
#< "$STATIONS" \
jq '.["@graph"] | map(.["@id"] + " -- " + .name) | .[]' -r | \
fzf --header 'Pick a station' | \
sed 's/ -- / /'\
)"

if [ "$station" = '' ] ; then
  >&2 echo 'No station selected'
  exit 1
fi

url="$(<<< "$station" cut -d' ' -f1)"
name="$(<<< "$station" cut -d' ' -f2-)"
id="BE.NMBS.${url##*/}"
#echo "$station"
#echo "ur: $url"
#echo "na: $name"
#echo "id: $id"

curl -s "https://api.irail.be/liveboard?format=json&id=$id" | \
#jq '.departures.departure'
TZ='Europe/Brussels' jq '.departures.departure |
map(
(.time | tonumber | strftime("%I:%M%p")) +
if ( .delay | tonumber ) > 0 then " \\033[31m+" + .delay + "\\033[0m" else "" end +
" -- " +
.station +
" " +
.platform +
" " +
.canceled +
" " +
.left
) |
.[]' -r
