#!/usr/bin/env sh
# from https://unix.stackexchange.com/a/125702/33933

search="$(printf '%s' "$1" | sed.escape.search)" && shift
replace="$(printf '%s' "$1" | sed.escape.replace)" && shift

sed "s/${search}/${replace}/g" "$@"
