#!/usr/bin/env python3

import os
import sys

path = sys.argv[1]
dirname, filename = os.path.split(path)

parts = filename.split('.')

linkname = '.'.join(parts[:-2]) + '.' + parts[-1]

linkpath = dirname + '/' + linkname if dirname else linkname

os.symlink(path, linkpath)
