#!/usr/bin/env sh

# Copied from
# https://github.com/chalk/ansi-regex/blob/02fa893d619d3da85411acc8fd4e2eea0e95a9d9/index.js#L2-L5

sed -e 's!'\
'[\x1b\x9b]'\
'[][()#;?]*'\
'\('\
'\('\
'\('\
'\('\
';[-a-zA-Z0-9\\/#&.:=?%@~_]+'\
'\)*\|'\
'[a-zA-Z0-9]+\(;[-a-zA-Z0-9\\/#&.:=?%@~_]*\)*'\
'\)\?\x07'\
'\)\|'\
'\(\([0-9]\{1,4\}\(;[0-9]\{0,4\}\)*\)\?[0-9A-PR-TZcf-ntqry=><~]\)'\
'\)'\
'!!g' "$@"
