#!/usr/bin/env sh

function packages {
	sed -E '/%.*$/d' |
	sed -E -n '/\\usepackage.*\{/p' |
	sed -E -e 's/^\s*\\usepackage[^\{]*\{//g' \
	       -e 's/\}.*//g' \
	       -e 's/^([^\.]*)$/\1.sty/g' |
	sort | uniq
}

function inputs {
	sed -E '/%.*$/d' |
	sed -E -n '/\\\input/p' |
	sed -E -e 's/\s//g' \
	       -e 's/\\input\{(.*)\}/\1/g' \
	       -e 's/^([^\.]*)$/\1.tex/g' |
	sort | uniq
}

function figures {
	sed -E '/%.*$/d' |
	sed -E -n '/\\includegraphics/p' |
	sed -E -e 's/\s//g' \
	       -e 's/\\includegraphics.*\{(.*)\}/\1/g' \
	       -e 's/^([^\.]*)$/\1.pdf/g' |
	sort | uniq
}

for path in "$@"; do
	if [ ! -e "$path" ] ; then continue; fi
	printf '%s\n' "$path"
	figures < "$path"
	sh "$0" $(packages < "$path")
	sh "$0" $(inputs < "$path")
done
