#!/usr/bin/env sh

cat "$@" |
sed \
-e '/^%/d' \
-e '/^\\begin{.*}$/d' \
-e '/^\\end{.*}$/d' \
-e 's/[^\]%.*$//g' \
-e 's/\\(//g' \
-e 's/\\)//g' \
-e 's/\\begin{.*}//g' \
-e 's/\\end{.*}//g' \
-e 's/\\.*{//g' \
-e 's/\\//g' \
-e 's/{//g' \
-e 's/}//g' |
tr '\n' ' ' |
sed \
-e 's/\s\s*/ /g' \
-e 's/^\s//g' \
-e 's/\s$//g'
