#!/usr/bin/env sh

cat | \
sed '/^%/d' | \
sed '/^\\begin{.*}$/d' | \
sed '/^\\end{.*}$/d' | \
sed 's/[^\]%.*$//g' | \
sed 's/\\(//g' | \
sed 's/\\)//g' | \
sed 's/\\begin{.*}//g' | \
sed 's/\\end{.*}//g' | \
sed 's/\\.*{//g' | \
sed 's/\\//g' | \
sed 's/{//g' | \
sed 's/}//g' | \
tr '\n' ' ' | \
sed 's/\s\s*/ /g' | \
sed 's/^\s//g' | \
sed 's/\s$//g' | \
cat
