#!/usr/bin/env python3

import sys
from args import parse

args, kwargs = parse(sys.argv[1:], [], {})

template = sys.stdin.read()

formatted = template.format(*args, **kwargs)

sys.stdout.write(formatted)
