#!/usr/bin/env sh

PLUGINS="$HOME/.config/dotfiles/plugins"

if [ "$#" -eq 0 ] ; then
  >&2 echo "usage: $0 <path>+"
  exit 1
fi

for path in "$@" ; do
  slug="$(basename "$path")"
  rm "$PLUGINS/$slug"
done
