#!/usr/bin/env bash

if [ $(id -u) == "0" ] ; then
  echo '! must NOT be run as root'
  exit 57
fi

echo '+ Parsing arguments'

### PARSING BEGIN ###

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
clean=false    # c
diff=false     # d
install=false  # i
modules=false  # m
npm=true       # n
homepage=false # o
pull=false     # p
restart=false  # r
sync=false     # s
tldr=false     # t
update=true    # u
vim=false      # v
_wait=false    # w
plugins=false  # x
pip=true       # y
fish=false     # z

function show_help ( ) {
  echo '! No help for the moment :(' ;
  echo ' > update script file is '"${BASH_SOURCE}"
}

while getopts "h?acdimnoprstuvwxyzCDIMNOPRSTUVWXYZ" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    a)  pull=true
        modules=true
        plugins=true
        clean=true
        sync=true
        install=true
        update=true
        restart=true
        vim=true
        fish=true
        tldr=true
        homepage=true
        ;;
    c)  clean=true
        ;;
    d)  diff=true
        update=false
        ;;
    i)  install=true
        ;;
    m)  modules=true
        ;;
    n)  npm=true
        ;;
    o)  homepage=true
        ;;
    p)  pull=true
        ;;
    s)  sync=true
        ;;
    r)  restart=true
        ;;
    t)  tldr=true
        ;;
    u)  update=true
        ;;
    v)  vim=true
        ;;
    w)  _wait=true
        ;;
    x)  plugins=true
        ;;
    y)  pip=true
        ;;
    z)  fish=true
        ;;
    C)  clean=false
        ;;
    D)  diff=false
        ;;
    I)  install=false
        ;;
    M)  modules=false
        ;;
    N)  npm=false
        ;;
    O)  homepage=true
        ;;
    P)  pull=false
        ;;
    R)  restart=false
        ;;
    S)  sync=false
        ;;
    T)  tldr=false
        ;;
    U)  update=false
        ;;
    V)  vim=false
        ;;
    W)  _wait=false
        ;;
    X)  plugins=false
        ;;
    Y)  pip=false
        ;;
    Z)  fish=false
        ;;
    esac
done

O="$(mktemp --tmpdir update_out_XXXXXXXX)"
E="$(mktemp --tmpdir update_err_XXXXXXXX)"

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

### PARSING END ###

function _exit ( ) {
  rm -f "$O" "$E"
  if $_wait ; then
    read
  fi
  exit "$1"
}

function _do ( ) {
  "$@" 1>"$O" 2>"$E"
  _check "$?" "$@"
}

function _check ( ) {

  if [ "$1" -ne 0 ] ; then
    echo '! NONZERO RETURN CODE'
    echo ' > There was an error!'
    >&1 cat "$O"
    >&2 cat "$E"

    echo    ' Q: Do you want to try again? [yes/no/skip]'
    echo -n ' A: '
    read reply

    case "$reply" in
      yes)
        shift
        _do "$@"
        ;;
      skip)
        echo ' > skipping'
        ;;
      *)
        _exit "$1"
        ;;
    esac

  fi

}

function _trap ( ) {
  echo '! TRAP'
  echo ' > There was an error!'
  _exit 70;
}

trap _trap SIGHUP SIGINT SIGTERM

echo '+ Looking up dotfiles'
DOTFILES="$(cat "$HOME/.config/dotfiles/location")"
PLUGINS="$HOME/.config/dotfiles/plugins"

if [ "$DOTFILES" = '' ] ; then
  echo '! Could not find dotfiles :('
  echo ' > Try running boostrap/dotfiles-udpate in the dotfiles directory!'
  echo ' > The update script should find the dotfiles after that :)'
  _exit 58
fi

echo ' * dotfiles @ '"$DOTFILES"

echo '+ Go to dotfiles'
_do cd "$DOTFILES"

if $pull ; then

  echo '+ Pull dotfiles'
  _do git pull

fi

if $modules ; then

  echo '+ Pull submodules'
  _do git submodule foreach "(git checkout master; git pull)"

fi

if $clean ; then

  echo '+ Clean up old software'
  sudo sh "$DOTFILES"/bootstrap/clean || _exit "$?"

fi

if $sync ; then

  echo '+ Update already installed software'

  echo " * aur"
  pacaur --noconfirm --noedit -Syu || _exit "$?"

  if $npm ; then
    echo " * npm"
    sudo sh "$DOTFILES"/bootstrap/update-npm u || _exit "$?"
  fi

  if $pip ; then
    echo " * pip"
    sudo sh "$DOTFILES"/bootstrap/update-pip u || _exit "$?"
  fi

fi

if $install ; then

  echo '+ Install new software'

  echo " * base"
  sudo sh "$DOTFILES"/bootstrap/install-base || _exit "$?"

  echo " * arch"
  sudo sh "$DOTFILES"/bootstrap/install-arch || _exit "$?"

  echo " * aur"
  sh "$DOTFILES"/bootstrap/install-aur || _exit "$?"

  if $npm ; then
    echo " * npm"
    sudo sh "$DOTFILES"/bootstrap/update-npm i || _exit "$?"
  fi

  if $pip ; then
    echo " * pip"
    sudo sh "$DOTFILES"/bootstrap/update-pip i || _exit "$?"
  fi

fi

if $restart ; then

  echo '+ Shutting down services'
  _do services.off

fi

if $diff ; then

  echo '+ Diff dotfiles'
  sh "$DOTFILES"/bootstrap/dotfiles-diff || _exit "$?"

fi

if $update ; then

  echo '+ Update dotfiles'
  sh "$DOTFILES"/bootstrap/dotfiles-update -f || _exit "$?"

fi

if $plugins ; then

  if [ -d "$PLUGINS" ] ; then
    echo '+ Plugins @ '"$PLUGINS"' :)'

    for plugin in $(ls -1a --color=never "$PLUGINS" | tail -c +6); do
      PLUGIN="$PLUGINS/$plugin"
      echo " * Plugin $plugin @ $PLUGIN"
      echo '  ° Go to '"$PLUGIN"
      _do cd "$PLUGIN"

      if $pull ; then

        echo '  ° Pull '"$PLUGIN"
        _do git pull

      fi

      if $diff ; then

        echo '  ° Diff '"$PLUGIN"
        sh "$PLUGIN"/dotfiles.diff || _exit "$?"

      fi

      if $update ; then

        echo '  ° Update '"$PLUGIN"
        sh "$PLUGIN"/dotfiles.update -f || _exit "$?"

      fi

    done

  else
    echo '+ No plugins @ '"$PLUGINS"' :('
  fi

fi

if $restart ; then

  echo '+ Enable ntpd'
  _do sudo systemctl enable ntpd # clock sync
  _do sudo systemctl start ntpd
  echo '+ Enable atd'
  _do sudo systemctl enable atd # at program
  _do sudo systemctl start atd
  echo '+ Enable devmon'
  _do sudo systemctl enable devmon@"$USER" # auto mount usb drives program
  _do sudo systemctl start devmon@"$USER"
  echo '+ Enable ssh-agent'
  _do systemctl --user enable ssh-agent
  _do systemctl --user start ssh-agent

  echo '+ Restarting services'
  _do services.on

fi

if $vim ; then

  echo '+ Update vim pluggins'
  vim.update || _exit "$?"

fi

if $fish ; then

  echo '+ Update fish pluggins'
  fish -c 'fisher up' || _exit "$?"

fi

if $tldr ; then

  echo '+ Update tldr cache'
  tldr --update || _exit "$?"

fi

if $homepage ; then

  echo '+ Update homepage'
  make -C "$HOME/.config/homepage/math" clean all

fi

if $_wait ; then
  echo '+ Done!'
fi

_exit 0
