#!/usr/bin/env bash

if [ $(id -u) == "0" ] ; then
  echo '! must NOT be run as root'
  exit 57
fi

O="$(mktemp /tmp/update.out.XXXXXXXX)"
E="$(mktemp /tmp/update.err.XXXXXXXX)"

echo '+ Parsing arguments'

### PARSING BEGIN ###

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
pull=false
modules=false
fonts=false
clean=false
sync=false
install=false
update=true
restart=false
vim=false
delay=false

function show_help ( ) {
  echo '! No help for the moment :(' ;
  echo ' > update script file is '"${BASH_SOURCE}"
}

while getopts "h?apmfcsiurvdPMFCSIURVD" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    a)  pull=true
        modules=true
        fonts=true
        clean=true
        sync=true
        install=true
        update=true
        restart=true
        vim=true
        ;;
    p)  pull=true
        ;;
    m)  modules=true
        ;;
    f)  fonts=true
        ;;
    c)  clean=true
        ;;
    s)  sync=true
        ;;
    i)  install=true
        ;;
    u)  update=true
        ;;
    r)  restart=true
        ;;
    v)  vim=true
        ;;
    d)  delay=true
        ;;
    P)  pull=false
        ;;
    M)  modules=false
        ;;
    F)  fonts=false
        ;;
    C)  clean=false
        ;;
    S)  sync=false
        ;;
    I)  install=false
        ;;
    U)  update=false
        ;;
    R)  restart=false
        ;;
    V)  vim=false
        ;;
    D)  delay=false
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

### PARSING END ###

function _exit ( ) {
  rm -f "$O" "$E"
  if $delay ; then
    read
  fi
  exit "$1"
}

function _do ( ) {
  "$@" 1>"$O" 2>"$E"
  _check "$?"
}

function _check ( ) {
  if [ "$1" -ne 0 ] ; then
    >&1 cat "$O"
    >&2 cat "$E"
    _exit "$1"
  fi
}

function _trap ( ) {
  _exit 70;
}

if $delay ; then
  trap _trap SIGHUP SIGINT SIGTERM
fi

echo '+ Looking up dotfiles'
DOTFILES="$(cat "$HOME/.config/dotfiles/location")"

if [ "$DOTFILES" = '' ] ; then
  echo '! Could not find dotfiles :('
  echo ' > Try running boostrap/dotfiles-udpate in the dotfiles directory!'
  echo ' > The update script should find the dotfiles after that :)'
  _exit 58
fi

echo ' * dotfiles @ '"$DOTFILES"

echo '+ Go to dotfiles'
_do cd "$DOTFILES"

if $pull ; then

  echo '+ Pull dotfiles'
  _do git pull

fi

if $modules ; then

  echo '+ Pull submodules'
  _do git submodule foreach "(git checkout master; git pull)"

fi

if $fonts ; then

  echo '+ Install fonts'
  _do sh modules/powerline-fonts/install.sh

fi

if $clean ; then

  echo '+ Clean up old software'
  _do sudo sh "$DOTFILES"/bootstrap/clean

fi

if $sync ; then

  echo '+ Update already installed software'
  bash "$DOTFILES"/bootstrap/update-software || _exit "$?"

fi

if $install ; then

  echo '+ Install new software'
  bash "$DOTFILES"/bootstrap/install-software || _exit "$?"

fi

if $restart ; then

  echo '+ Shutting down services'
  _do services.off

fi

if $update ; then

  echo '+ Update dotfiles'
  sh "$DOTFILES"/bootstrap/dotfiles-update -f || exit "$?"

fi

if $restart ; then

  echo '+ Enable ntpd'
  _do sudo systemctl enable ntpd # clock sync
  _do sudo systemctl start ntpd
  echo '+ Enable atd'
  _do sudo systemctl enable atd # at program
  _do sudo systemctl start atd

  echo '+ Restarting services'
  _do services.on

fi

if $vim ; then

  echo '+ Update vim pluggins'
  vim.update || _exit "$?"

fi

if $delay ; then
  echo '+ Done!'
fi

_exit 0
