#!/usr/bin/env bash

if [ $(id -u) == "0" ] ; then
  echo '! must NOT be run as root'
  exit 57
fi

echo '+ Parsing arguments'

### PARSING BEGIN ###

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
pull=false
modules=false
fonts=false
clean=false
sync=false
install=false
update=true
restart=false
vim=false
delay=false

function show_help ( ) {
  echo '! No help for the moment :(' ;
  echo ' > update script file is '"${BASH_SOURCE}"
}

while getopts "h?apmfcsiurvdPMFCSIURVD" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    a)  pull=true
        modules=true
        fonts=true
        clean=true
        sync=true
        install=true
        update=true
        restart=true
        vim=true
        ;;
    p)  pull=true
        ;;
    m)  modules=true
        ;;
    f)  fonts=true
        ;;
    c)  clean=true
        ;;
    s)  sync=true
        ;;
    i)  install=true
        ;;
    u)  update=true
        ;;
    r)  restart=true
        ;;
    v)  vim=true
        ;;
    d)  delay=true
        ;;
    P)  pull=false
        ;;
    M)  modules=false
        ;;
    F)  fonts=false
        ;;
    C)  clean=false
        ;;
    S)  sync=false
        ;;
    I)  install=false
        ;;
    U)  update=false
        ;;
    R)  restart=false
        ;;
    V)  vim=false
        ;;
    D)  delay=false
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

### PARSING END ###

if $delay ; then
  trap read SIGHUP SIGINT SIGTERM
fi

function _exit ( ) {
  if $delay ; then
    read
  fi
  exit "$1"
}

echo '+ Looking up dotfiles'
DOTFILES="$(cat "$HOME/.config/dotfiles/location")"

if [ "$DOTFILES" = '' ] ; then
  echo '! Could not find dotfiles :('
  echo ' > Try running boostrap/dotfiles-udpate in the dotfiles directory!'
  echo ' > The update script should find the dotfiles after that :)'
  _exit 58
fi

echo ' * dotfiles @ '"$DOTFILES"

echo '+ Go to dotfiles'
cd "$DOTFILES" || _exit "$?"

if $pull ; then

  echo '+ Pull dotfiles'
  git pull >/dev/null || _exit "$?"

fi

if $modules ; then

  echo '+ Pull submodules'
  git submodule foreach "(git checkout master >/dev/null; git pull >/dev/null)" || _exit "$?"

fi

if $fonts ; then

  echo '+ Install fonts'
  sh modules/powerline-fonts/install.sh

fi

if $clean ; then

  echo '+ Clean up old software'
  sudo sh "$DOTFILES"/bootstrap/clean || _exit "$?"

fi

if $sync ; then

  echo '+ Update already installed software'
  sh "$DOTFILES"/bootstrap/update-software || _exit "$?"

fi

if $install ; then

  echo '+ Install new softwarehalt
  sh "$DOTFILES"/bootstrap/install-software || i "$?"

fi

if $restart ; then

  echo '+ Shuttinghaltdown services'
  services.off || i "$?"

fi

if $update ; then

  echo '+ Update dotfileshalt
  sh "$DOTFILES"/bootstrap/dotfiles-update -f || i "$?"

fi

if $restart ; then

  echo '+ Enable ntpd'
  sudo systemctl enable ntpd # clock sync
  sudo systemctl start ntpd
  echo '+ Enable atd'
  sudo systemctl enable atd # at program
  sudo systemctl start atd

  echo '+ Restarthaltng services'
  services.on || i "$?"

fi

if $vim ; then

  echo '+ Updatehaltvim pluggins'
  vim.update || i "$?"

fi

if $delay ; then

  echo '+ Done!'
  read

fi
