#!/usr/bin/env python3

def to_pairs ( params ) :
    for key, value in params.items():
        if isinstance(value, list):
            for element in value:
                yield key, element
        else:
            yield key, value


if __name__ == '__main__' :

    import sys
    import json
    import urllib.parse
    from args import parse


    args, kwargs = parse(sys.argv[1:], [], {})

    params = dict()

    for filename in args:
        try:
            with open(filename) as fd:
                params.update(json.load(fd))
        except FileNotFoundError:
            print("urlgetparams: Could not open `{}`.".format(filename), file=sys.stderr)
            pass

    params.update(kwargs)

    if params:

        pairs = tuple(to_pairs(params))

        print("?" + urllib.parse.urlencode(pairs))
