#!/usr/bin/env sh

printf "%s\n%s\n" y n | sudo pacman -Sc

while true ; do

  unrequired="$(pacman -Qdtq)"

  if [ -z "$unrequired" ] ; then
    break
  fi

  # shellcheck disable=SC2086
  sudo pacman -R $unrequired --noconfirm

done

sudo journalctl --vacuum-size 50M
