#!/usr/bin/env sh

sudo paccache -rk3
sudo paccache -ruk0

while true ; do

  unrequired="$(pacman -Qdtq)"

  if [ -z "$unrequired" ] ; then
    break
  fi

  # shellcheck disable=SC2086
  sudo pacman -R $unrequired --noconfirm

done

sudo journalctl --vacuum-size 50M
