#!/usr/bin/env bash

pollinterval="$1" ; shift

O="$(mktemp --tmpdir "${USER}-watchless-buf.XXXXXXXX")"
2>/dev/null $@ > "$O" ;

(while true ; do
	sleep "$pollinterval"
	T="$(mktemp --tmpdir "${USER}-watchless-src.XXXXXXXX")"
	2>/dev/null $@ > "$T"
	cat "$T" > "$O" # avoids less to crash
	# also `mv` does not work for some reason
	rm -f "$T"
done) &
pid="$!"

function clean {
	rm -f "$O"
	kill -9 "$pid"
	exit
}

trap clean SIGHUP SIGINT SIGTERM

less -R "$O"
clean
