#!/usr/bin/env sh

if [ "$#" -ge 1 ] ; then
  selection="$1"
else
  selection="$(xsel -b 2>/dev/null)"
  if [ -z "$selection" ] ; then
    >&2 echo "No command line arguments and selection is empty :("
    exit 11
  else
    if ! ask "Archive '$selection'?" ; then
      exit 12
    fi
  fi
fi

ROOT='https://web.archive.org'
url="$selection"

curl -v 2>&1 >/dev/null "${ROOT}/save/${url}" |
sed -n 's@^< content-location: @'"${ROOT}"'@p'
