#!/usr/bin/env sh

languages="en\nfr\n"


lang=$(printf '%b' "$languages" | dmenu_center --rest -p ' ' -sb '#9791D9')

if [ "$lang" = '' ] ; then
	exit 2
fi


q=$(ui.dialog.input -p ' '"$lang"'.wikipedia.org' -sb '#9791D9')

if [ "$q" = '' ] ; then
	exit 1
fi

query=$(printf '%s' "$q" | urlencode)

wb --new-window 'https://'"$lang"'.wikipedia.org/wiki/Special:Search?search='"$query"
