#!/usr/bin/env node

const fs = require('fs') ;
const filename = process.argv[2] ;
const YAML = require('js-yaml') ;

const readStream = fs.createReadStream( filename || '/dev/stdin' ) ;
const writeStream = process.stdout ;

let yaml = '';

readStream.on('data', function (chunk) { yaml += chunk; });

readStream.on('end', function () {
  const data = YAML.load(yaml);
  const json = JSON.stringify(data);
  writeStream.write(json);
  writeStream.write('\n');
});
