#!/usr/bin/env sh

q=$(ui.dialog.input -p '' -sb '#C61800')

if [ "$q" = '' ] ; then
	exit 1
fi

query=$(echo -n "$q" | urlencode)

wb --new-window 'https://www.youtube.com/results?search_query='"$query"
