
figures=

all: $(figures) .updated

.updated:
	touch .updated

clean:
	rm -f $(figures) .updated

#figure-i.pdf: figures.ipe
	#ipetoipe -pdf -export -view 1-2 figures.ipe figure-i.pdf
	#touch .updated
